#!/usr/bin/env sh

# https://github.com/koekeishiya/yabai/issues/203#issuecomment-700527407

## backward
#yabai -m query --spaces --space \
#  | jq -re ".index" \
#  | xargs -I{} yabai -m query --windows --space {} \
#  | jq -sre "add | map(select(.minimized != 1)) | sort_by(.display, .frame.y, .frame.y, .id) | nth(index(map(select(."has-focus" == true))) - 1).id" \
#  | xargs -I{} yabai -m window --focus {}

# v4+
# https://github.com/koekeishiya/yabai/issues/203#issuecomment-1088641580
if [ "$(yabai -m query --spaces --space | jq -r '.type')" = "stack" ]; then (yabai -m window --focus stack.prev || yabai -m window --focus stack.last); else yabai -m window --focus prev || yabai -m window --focus last; fi

